{
  imports = [
    ../../../../modules/home-manager/nixvim/nixvim.nix
    ../../../../modules/home-manager/terminal/bundle.nix
    ../../../../modules/home-manager/btop.nix
    ../../../../modules/home-manager/firefox.nix
    ../../../../modules/home-manager/gpg.nix
    ../../../../modules/home-manager/hyprlock.nix
    ../../../../modules/home-manager/keyboard.nix
    ../../../../modules/home-manager/lazygit.nix
    ../../../../modules/home-manager/mpv.nix
    ../../../../modules/home-manager/ncspot.nix
    ../../../../modules/home-manager/theme.nix
    ../../../../modules/home-manager/wofi.nix
    ../../../../modules/home-manager/xdg.nix
    ../../../../modules/home-manager/zathura.nix
    ./wms/hypr/bundle.nix
    ./wms/hyprpanel.nix
    ./git.nix
    ./lan-mouse.nix
  ];
}
