{
  imports = [
    ../../../../modules/nixos/modules/android.nix
    ../../../../modules/nixos/modules/boot.nix
    ../../../../modules/nixos/modules/console.nix
    ../../../../modules/nixos/modules/docker.nix
    ../../../../modules/nixos/modules/env.nix
    ../../../../modules/nixos/modules/gpg.nix
    ../../../../modules/nixos/modules/hypr.nix
    ../../../../modules/nixos/modules/i18n.nix
    ../../../../modules/nixos/modules/ld.nix
    ../../../../modules/nixos/modules/nh.nix
    ../../../../modules/nixos/modules/settings.nix
    ../../../../modules/nixos/modules/sound.nix
    ../../../../modules/nixos/modules/stylix.nix
    ../../../../modules/nixos/modules/sudo.nix
    ../../../../modules/nixos/modules/zsh.nix
    ./packages.nix
  ];
}
