{
  imports = [
    ./cmp.nix
    ./comment.nix
    ./conform.nix
    ./extra-plugins.nix
    ./fidget.nix
    ./git-blame.nix
    ./lazygit.nix
    ./lsp.nix
    ./lspsaga.nix
    ./mini.nix
    ./neotree.nix
    ./nix.nix
    ./otter.nix
    ./telescope.nix
    ./transparent.nix
    ./ts-autotag.nix
    ./undotree.nix
  ];
}
