{
  imports = [
    ./actions-preview.nix
    ./cmp.nix
    ./comment.nix
    ./conform.nix
    ./fidget.nix
    ./git-blame.nix
    ./lazygit.nix
    ./lsp.nix
    ./lspsaga.nix
    ./mini.nix
    ./neotree.nix
    ./nix.nix
    ./telescope.nix
    ./transparent.nix
    ./ts-autotag.nix
  ];
}
